## Data Science Society Workshop 3: Numpy Solutions
Run this code cell before attempting the problems!

In [ ]:
# Imports Numpy module
import numpy as np

### Debugging Problems
#### 1) Generating Arrays
Output should be:

[0 4 8 5]

[0 0.1 0.2 0.3 0.4 ... 9.6 9.7 9.8 9.9 10] 

[[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]] Note that here every four zeros will be on a different line.

In [ ]:
## PROBLEM CODE CELL
# Generates an array [0 4 8 5] Hint: Think about the type of input for np.array!
x = np.array(0,4,8,5)
print(x)

# Generates array with spacing 0.1 and values ranging from 0 to 10 Hint: Is there another more suitable function?
x = np.linspace(0,10,0.1)
print(x)

# Generates a 4x4 array of zeros Hint: Something is missing from the input
x = np.zeros(4,4)
print(x)

In [ ]:
## SOLUTION CODE CELL
# Generates an array [0 4 8 5]
x = np.array([0,4,8,5])
print(x)

# Generates array with spacing 0.1 and values ranging from 0 to 10 
x = np.arange(0,10.1,0.1)
print(x)

# Generates a 4x4 array of zeros 
x = np.zeros((4,4))
print(x)

'''Note: We could use **np.linspace(0,10,101)** for the second array but 
if you want a specific spacing **arange** is probably more ideal.
If you want a specific number of points **linspace** is probably the best choice.'''

#### 2) Array Slicing 
Here we have a code cell that defines a bunch of arrays that are to be sliced. Run this cell but do not change the code in this cell! 

In [ ]:
## SETUP CODE CELL DO NOT CHANGE 
# Generates an array from list
x = np.array([2,7,9,3,6])
print(x)

# Generates an array from lists
y = np.array([[8,3,2],[1,4,9],[5,3,2]])
print(y)

Some poor attempts have been made to slice the arrays ````x```` and ````y```` which have been defined above. Correct these so that the desired values are printed as indicated by the comments. The correct output should be:

2

[9 3 6]

[3 4 3]

4

In [ ]:
## PROBLEM CODE CELL
# Prints 1st value of array x Hint: Think of how Python numbers different indices
print(x[1])

# Prints 2nd to last value of array x
print(x[2;])

# Prints second column of array y Hint: How are rows and columns seperated when slicing?
print(y[:1])

# Prints second diagonal value of array y
print(y[1:1])

In [ ]:
## SOLUTION CODE CELL
# Prints 1st value of array x
print(x[0])

# Prints 2nd to last value of array x
print(x[2:])

# Prints second column of array y
print(y[:,1])

# Prints second diagonal value of array y
print(y[1,1])

#### 3) Array Functions
This problem has another setup code cell to run before attempting to solve the problems.

In [ ]:
## SETUP CODE CELL DO NOT CHANGE
# Generates an array of all even numbers from 2 to 20
x = np.linspace(2,20,10)
print(x)

# Generates an array of all even numbers from 22 to 40
y = np.linspace(22,40,10)
print(y)

Correct output should be: 

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]

[22. 24. 26. 28. 30. 32. 34. 36. 38. 40.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40.]

In [ ]:
## PROBLEM CODE CELL
# Redefines x as array shifted to the left by 2 
x = np.roll(x,2)
print(x)

# Merges the specified arrays into a new array 
z = np.concatenate(y,x,y)
print(z)

In [ ]:
## SOLUTION CODE CELL
# Redefines x as array shifted to the left by 2
x = np.roll(x,-2)
print(x)

# Merges the specified arrays into a new array
z = np.concatenate([y,x,y])
print(z)

#### 4) Redefining Array Values
The setup code cell will define a ````x```` to be a $10\times10$ array of zeros. The code in the problem code cell attempts to change the every value in a row to be equal to the row index. 

In [ ]:
## SETUP CODE CELL DO NOT CHANGE
# Creating a 10x10 array of zeros
x = np.zeros((10,10))
print(x)

If you have sorted the code correctly then all values in the first row will be $0$, $1$ in the second, $2$ in the third and so forth.

In [ ]:
## PROBLEM CODE CELL
# Loop over all rows Hint: Something is missing from the range argument
for i in range(x):
    # Redefines the current array value as the row index Hint: How do you redefine array values
    x = i 

# Outputs x
print(x)

In [ ]:
## SOLUTION CODE CELL
# Loop over all rows 
for i in range(len(x)):
    # Redefines the current array value as the row index
    x[i] = i 

# Outputs x
print(x)

### Coding From Scratch
#### 1) Generating Arrays
In the code cell below define and print a set of arrays defined ````x````, ````y```` and ````z````. The array ````x```` should be take the form [10 12 9 2 20], ````y```` should have $101$ values from $10$ to $20$ inclusive and ```z``` should be a $2\times3$ array of ones.

In [ ]:
## SOLUTION CODE CELL
# Generates an array x as [10 12 9 2 20]
x = np.array([10,12,9,2,20])
print(x)

# Generates an array y with 101 values from 10 to 20 inclusive
y = np.linspace(10,20,101)
print(y)

# Generates an array z as a 2x3 array of ones
z = np.ones((2,3))
print(z)

#### 2) Array Functions
Using the available Numpy functions on array ````x```` from problem $1$, find the average and the standard deviation of the value in this array. Redefine ````x```` as an array with all these values sorted in numerical order.

In [ ]:
## SOLUTION CODE CELL
# Average of values in array x
print(np.mean(x))

# Standard deviation of values in array x
print(np.std(x))

# Sorts values of x
x = np.sort(x)
print(x)

#### 3) Redefining Array Variables
Generate an array ````x```` to be a $10\times10$ array of zeros. Redefine its diagonal components (from left to right) to equal one. Hint: You will likely require two loops along with a conditional statement that determines whether the current slice is a diagonal component. Think carefully about what this condition might be.

In [ ]:
## SOLUTION CODE CELL
# Generates a 10x10 array of zeros
x = np.zeros((10,10))

# Loops over the rows of x
for i in range(len(x)):
    # Loops over the columns of x
    for j in range(len(x)):
        # Identifies whether component is on the diagonal
        if i == j:
            x[i,j] = 1

print(x)    

#### 4) Random Numbers
The popular role-playing game Dungeons and Dragons utilises a variety of die with varying numbers of sides. For instance the d20 dice has 20 sides and a d10 has 10. Create a function that takes an integer as the argument. This integer specifies the number of sides the dice has. Your function should output a number that you could get by rolling the specified type of dice. Once you think your function works modify it so it creates an array of dice rolled values. The length of the array should be specifyed by an additional argument for your function. Take the average of these values to check if your function works as expected for an array of $1000$ values. In general the average for rolling a certain dice should be half the maximum value plus $0.5$, so $5.5$ for a d10 for example. You should get close to this value but will likely be off slightly. 

In [ ]:
## SOLUTION CODE CELL
# Defines a dice rolling function
def dice(x,n):
    '''Function that rolls n dice with x sides'''
    
    # Rolls n dice with x sides
    return np.random.randint(1,x+1,n)

# Using the function to roll a d10 1000 times
roll = dice(10,1000)

# Average of all the rolls
np.mean(roll)

### Further Work (Optional)
#### 1) Vectors and Matrices
Given two vectors: $$ \textbf{A} = \begin{pmatrix} 1 \\ 2 \\ -1 \end{pmatrix}, \textbf{B} = \begin{pmatrix} 4 \\ -1 \\ 5 \end{pmatrix}. $$ Using Numpy find: $$\textbf{A}\cdot\textbf{B}, $$ $$\textbf{A}\times\textbf{B}, $$ $$\textbf{A}\otimes\textbf{B}. $$ Find the eigenvalues resulting from the matrix that is the result of the outer product between the two vectors.

In [ ]:
## SOLUTION CODE CELL 
# Generating the vectors
A = np.array([1,2,-1])
B = np.array([4,-1,5])

# Scalar product
print(np.dot(A,B))

# Vector product
print(np.cross(A,B))

# Tensor Product
AB = np.outer(A,B)
print(AB)

# Eigenvalues of the matrix tensor product
print(np.linalg.eigvals(AB))

#### Levi-Civita Tensor (Optional x2)
The Levi-Civita tensor is a 3rd order tensor defined such that:  $$ \epsilon_{ijk} = 
    \begin{cases}
      0 & if \>\> i=j \>\> or \>\> j=k \>\> or \>\> i=k \\
      1 & for \>\> even \>\> passes \\
      -1 & for \>\> odd \>\> passes
    \end{cases}
$$
Even passes meaning if you wrote out the indices $i,j$ and $k$ out infinitely it would be equivalent to writing 1,2,3 out infinitely (for three dimensions at least). Odd passes mean the opposite is true provided none of the indices are equal as then $\epsilon_{ijk}=0$. We can represent this three index structure as a 3D Numpy array. Generate such an array using loops and conditional statements. Start with a $3\times3\times3$ array of ones and turn the relevent values into zeros. Some of you're conditional statements will require multiple conditions so use ````and```` or ````or```` in such cases.

In [ ]:
## SOLUTION CODE CELL
# Generates 3x3x3 array to store values
levi_civita = np.ones((3,3,3))

# Loop over all spatial dimensions
for i in range(3):
    for j in range(3):
        for k in range(3):
            # Any equal indexes returns zero
            if i==j or i==k or j==k:
                levi_civita[i,j,k] = 0
            
            # Any odd pass returns -1
            if i == 1 and j == 0 and k == 2:
                levi_civita[i,j,k] = -1
            if i == 0 and j == 2 and k == 1:
                levi_civita[i,j,k] = -1
            if i == 2 and j == 1 and k == 0:
                levi_civita[i,j,k] = -1
            
            # Since we have created an array of ones no need to cycle through even passes
            
print(levi_civita)